### ISSUE TITLE
Downloads failing

### ISSUE THREAD

**Issue by kkitay** [fallaciousreasoning/CalibreLibgenStore#9]
I'm consistently getting download fail errors.

```
Starting job: Downloading War and Peace (English, 1.71Mb).epub 
Job: "Downloading War and Peace (English, 1.71Mb).epub" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 83, in start_work
  File "calibre/gui2/ebook_download.py", line 85, in __call__
  File "calibre/gui2/ebook_download.py", line 97, in _download
Exception: No file specified to download.
 
Called with args: (<calibre.gui2.ui.Main object at 0x1189e0160>, None, None, 'War and Peace (English, 1.71Mb).epub', '', True, [], <bound method StorePlugin.create_browser of <calibre_plugins.libgen_fiction.LibgenStore object at 0x134bdc970>>) {'notifications': <queue.Queue object at 0x134883700>, 'abort': <threading.Event object at 0x134883820>, 'log': <calibre.utils.logging.GUILog object at 0x134883760>} 
```

**Comment by hamzamaal** [comment]
+1 exactly the same error.

**Comment by fallaciousreasoning** [comment]
Hey guys. Sorry, I haven't really done much on this for the last little while - I've got a bit going on in my personal life at the moment. I'll get to it eventually but I can't promise it'll be soon

**Comment by fallaciousreasoning** [comment]
Okay, this should be fixed in [v0.4.2](https://github.com/fallaciousreasoning/CalibreLibgenStore/releases/tag/v0.4.2)

**Comment by hamzamaal** [comment]
Thanks, working now, just have to make sure that the open in external browser is unchecked otherwise, it throws the same error. Before it threw the error whether the button was checked or not.

**Comment by kkitay** [comment]
I upgraded to the latest Calibre and the issue is back @fallaciousreasoning 

```
Starting job: XYZ 
Job: "XYZ.epub" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre/gui2/ebook_download.py", line 82, in __call__
  File "calibre/gui2/ebook_download.py", line 98, in _download
  File "calibre/gui2/ebook_download.py", line 65, in download_file
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by Tenome** [comment]
Plugin's not working for me either (actually, it doesn't return any results at all).
Edit: Updating to the current Github version (not release) sorta fixes it. It only shows a small portion of the search results though and even then, the download doesn't work.
